channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=25.0.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.1.1
  - numpy==2.2.3
  - pandas==2.2.2
  - psutil==5.9.6
  - scikit-learn==1.6.1
  - scipy==1.15.1
name: mlflow-env
